### ISSUE TITLE
Gradle Version?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [natocesarrego/slider#2]
Can you please advise as to what version of Gradle should be used to get this to build?

Tried with 4.10, 4.10.1, and 6.2.2. All error out with ..

`Could not find method compileOnly() for arguments [{group=com.liferay, name=com.liferay.dynamic.data.mapping.api, version=5.7.0}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.`

**Comment by natocesarrego** [comment]
Hi @mfreeman-xtivia,

Please check this comment [here](https://issues.liferay.com/browse/LPS-98417?focusedCommentId=2123234&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2123234) in Jira to get your answer. 🙂 

Best.
