### ISSUE TITLE
How to generate JS files from Soy Templates

### ISSUE THREAD

**Issue by alexandresjunior** [natocesarrego/slider#6]
Hi, guys! At first, nice work! I've been using this project as a reference for me and my team. I've noticed that for each soy template file, there is a js file automatically generated from that one. My question is: how can I generated those js files? Thanks!

**Comment by alexandresjunior** [comment]
just noticed that they are generated after deploying the module ;)

**Comment by natocesarrego** [comment]
Good to know, @alexandresjunior! :smile: 

The JS files are generated during the compile time of the OSGI module, e.g. the Slider code. Therefore, since the compilation is always performed before a deploy then the deploy, behind the scenes, triggers the compilation. :wink:
