### ISSUE TITLE
Could you add an example of this module using the most recent react components?

### ISSUE THREAD

**Issue by abdulzeedo** [natocesarrego/slider#7]
Hi

I saw that Liferay moved from soy templates to react components and wrapping their fields with "FieldBase" react component. Could you provide an example of slider using the most recent module changes as blueprint?

**Comment by natocesarrego** [comment]
Sure, @abdulzeedo! Please check an existing example [here](https://github.com/marcosapmf/slider).

Cheers! :slightly_smiling_face:

**Comment by abdulzeedo** [comment]
Completely made my day. `--js-framework react` is something I haven't been using in my blade templates. So I never got the react version.
